#!/bin/bash

# Get repository name
if [ $(git rev-parse --is-bare-repository) = true ]
then
    REPOSITORY_BASENAME=$(basename "$PWD") 
else
    REPOSITORY_BASENAME=$(basename $(readlink -nf "$PWD"/..))
fi

# Get branch
branch=$(git rev-parse --symbolic --abbrev-ref $1)

# Set-up script and python path
SCRIPT_PATH="/home/$(whoami)/repo-scripts/updateDbOnPush.py" 
PYTHON="/usr/bin/python"

# Get commit hash
REVISION=$(git rev-parse HEAD)

# call script via the interrupter     
$PYTHON $SCRIPT_PATH $REPOSITORY_BASENAME $branch $REVISION

# Echo to user
echo Update pushed to branch $branch
exec git update-server-info